# -*- coding: utf-8 -*-
"""interface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQAaWmoc2yFXcJssZLKnwpIepez2L_QF
"""

from abc import ABC, abstractmethod


class Car(ABC):
    @abstractmethod
    def start_engine(self):
        pass

    @abstractmethod
    def stop_engine(self):
        pass


class Sedan(Car):
    def start_engine(self):
        print("Sedan engine started.")

    def stop_engine(self):
        print("Sedan engine stopped.")


class SUV(Car):
    def start_engine(self):
        print("SUV engine started.")

    def stop_engine(self):
        print("SUV engine stopped.")


    # Program to the Car interface, not the specific implementations
mycar = Sedan()  # Can easily switch to SUV without changing the client code
mycar.start_engine()
mycar.stop_engine()

    # Switch to another implementation
mycar = SUV()
mycar.start_engine()
mycar.stop_engine()