# -*- coding: utf-8 -*-
"""Observer_Pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUUzAoRpHUE7fZL_B-oy-Naezz8Ngsao
"""

class Celebrity:
    def __init__(self):
        self._fans = []
        self.state = None

    def attach(self, fan):
        self._fans.append(fan)

    def remove(self, fan):
        self._fans.remove(fan)

    def notify_fans(self):
        for fan in self._fans:
            fan.update(self)

    def set_state(self, new_state):
        self.state = new_state
        self.notify_fans()

    def get_state(self):
        return self.state


class Fan:
    def __init__(self, name):
        self.name = name
        self._celebrities = []

    def update(self, celebrity):
        print(f"{self.name}, notification for you! {celebrity.get_state()}")

    def add_celebrity(self, celebrity):
        self._celebrities.append(celebrity)
        celebrity.attach(self)

    def remove_celebrity(self, celebrity):
        self._celebrities.remove(celebrity)
        celebrity.remove(self)



f1 = Fan("Leo")
f2 = Fan("Brad")
f3 = Fan("Lee")

c1 = Celebrity()

f1.add_celebrity(c1)
f2.add_celebrity(c1)
f3.add_celebrity(c1)

c1.set_state("Celebrity posted a new photo")   #Leo, notification for you! Celebrity posted a new photo
                                               #Brad, notification for you! Celebrity posted a new photo
                                               #Lee, notification for you! Celebrity posted a new photo